#!/bin/sh
VERSION=$1
if [ "$VERSION" == "" ]; then
 if [ -f version ]; then
  VERSION=`cat version`
 else
  echo "run with $0 version_tag"
  exit 1
 fi
fi
echo "Buidling docker container for version $VERSION"
docker system prune -a -f
docker build -t plexamp:$VERSION -f Dockerfile .

