version: '3'
services:
  plexamp:
    container_name: plexamp
    privileged: true
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /data/extensiondata/plexamp/:/home/plexamp:rw
      - /run:/run:rw
    restart: unless-stopped
    group_add:
      - 2001

