version: '3'
services:
  plexamp:
    container_name: plexamp
    network_mode: "host"
    image: ghcr.io/hifiberry/extension_plexamp:4.10.1
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    volumes:
      - /etc/hostname:/etc/hostname
      - /etc/plexamp.token:/etc/plexamp.token
      - /data/extensiondata/plexamp/:/home/plexamp:rw
      - /run:/run:rw
    restart: unless-stopped
    group_add:
      - 2001
    privileged: true

