#!/bin/bash

# Check if the system has been connected
if [ -f /home/plexamp/.local/share/Plexamp/Settings/%40Plexamp%3Auser%3Atoken ]; then
    echo "Player connected, do not use claimtoken"
    # If the file exists, run the Node.js script
    node js/index.js
else
    # If the file does not exist, run the expect script and add the token
    echo "Player not connected, add token"
    expect claimtoken
fi

sleep 10
